/* Companion presentation. Inlined into local, exported and public HTML. No fetching here. */
const companionMedia=matchMedia('(max-width:700px)');
const matchKey='predecessor-match-v2',prefsKey='predecessor-companion-v1';
const copyValue=v=>JSON.parse(JSON.stringify(v));
let companionPrefs={recent:[],favorites:[],large:false,installSeen:false,homeQuery:''};
try{Object.assign(companionPrefs,JSON.parse(localStorage.getItem(prefsKey)||'{}'));}catch{}
if(!Array.isArray(companionPrefs.recent))companionPrefs.recent=[];if(!Array.isArray(companionPrefs.favorites))companionPrefs.favorites=[];
let undoAction=null,undoTimer=null,historyApplying=false,linkApplied='',companionError='';
S.liveContexts={};S.liveVariant=null;
try{const m=JSON.parse(sessionStorage.getItem(matchKey)||'{}');if(m.v===2&&m.contexts&&typeof m.contexts==='object'&&!Array.isArray(m.contexts))S.liveContexts=m.contexts;}catch{}
function saveCompanionPrefs(){try{localStorage.setItem(prefsKey,JSON.stringify(companionPrefs));}catch{toast('Preferences could not be saved on this device.');}}
function saveMatchSession(){try{sessionStorage.setItem(matchKey,JSON.stringify({v:2,contexts:S.liveContexts}));}catch{ /* Usable in memory when storage is unavailable. */ }}
function contextFor(p){const c=S.liveContexts[p.slug+'|'+p.role];return c&&typeof c==='object'?c:{owned:[],state:'even',priority:''};}
function coachEnemies(p){return S.enemies.filter(e=>e.slug!==p.slug);}
function adviceFor(p){const enemies=coachEnemies(p),ctx={...contextFor(p)};if(ctx.primaryThreat&&!enemies.some(e=>e.slug===ctx.primaryThreat))delete ctx.primaryThreat;return E.adaptBuild(p,S.locks.filter(a=>a.slug!==p.slug).concat(p),enemies,ctx);}
function freshnessHTML(){
 const rows=[['Mechanics',B?.sources?.pred_game_data||B?.sources?.omeda_heroes],['Statistics',B?.sources?.statz_hero_pages]];
 const dated=rows.map(([label,s])=>label+': '+date(s?.fetched_at)+(s?.status==='retained'?' · retained':''));
 const stale=rows.some(([,s])=>!Number.isFinite(Date.parse(s?.fetched_at))||Date.now()-Date.parse(s.fetched_at)>30*3600000||s?.status==='retained');
 return `<p class="coach-date ${stale||!navigator.onLine||connectionLost?'warning':''}">${!navigator.onLine||connectionLost?'Connection unavailable · saved data. ':stale?'Older or incomplete source data. ':''}${esc(B?.bracket?.label||'Bracket unavailable')} · ${esc(dated.join(' · '))}</p>`;
}
function coachHTML(p,{compact=false}={}){
 let a;try{a=adviceFor(p);}catch(e){return `<section class="panel coach"><h2>Recommendation unavailable</h2><p>${esc(e.message)}</p><button data-route="data">Inspect sources</button></section>`;}
 const enemies=coachEnemies(p),key=p.slug+'|'+p.role,attr=`data-coach-key="${esc(key)}"`;
 const controls=`<div class="coach-controls"><label>My hero is<select ${attr} data-coach-field="state">${options([['ahead','Ahead'],['even','Even'],['behind','Behind']],a.state)}</select></label><label>Primary threat<select ${attr} data-coach-field="primaryThreat">${options(enemies.map(e=>[e.slug,name(e.slug)+' · '+labels[e.role]]),a.primaryThreat||'','No primary threat')}</select></label><label>Urgent need<select ${attr} data-coach-field="priority">${options(E.itemNeeds.filter(n=>!n.manual).map(n=>[n.id,n.label]),a.priority,'Normal timing')}</select></label></div>`;
 const info=`<p class="muted">Judge your hero’s farm and power curve. Enemy equipment is unknown until you choose a need.</p>`;
 const next=a.available?(a.nextPurchase?`<h2>Next: ${esc(a.nextPurchase.name)}</h2>${badge(a.nextPurchase.kind==='core'||a.nextPurchase.kind==='baseline'?'Reviewed':'Calculated',a.nextPurchase.kind==='core'?'reviewed':'calculated')}`:'<h2>Six completed items owned</h2><p>No purchase or sale suggested.</p>'):`<h2>Recommendation unavailable</h2><p>${esc(a.unavailableReason)}</p>`;
 return `<section class="panel coach" aria-label="Build Coach"><div class="coach-next">${next}</div>${controls}${compact?'':info}${freshnessHTML()}${a.available?`<p class="coach-reason">${esc(a.explanations[0])}</p><ol class="build-path coach-path">${a.slots.map((s,i)=>`<li><span class="item-position">${i+1} · ${esc(s.label)}</span>${itemButton(s.name)}</li>`).join('')}</ol>`:'<button data-route="data">Inspect sources & accuracy</button>'}<details><summary>Advanced details · why this path</summary><div class="detail-content">${info}<p>Reviewed for ${esc(a.evidence.reviewed.patch||'unverified')} · ${esc(date(a.evidence.reviewed.date))}. Editorial reference remains Gold+; observations use ${esc(B.bracket?.label)}.</p>${a.explanations.slice(1).map(t=>`<p>${esc(t)}</p>`).join('')}${a.changes.map(c=>`<p><strong>Position ${c.position}: ${esc(c.item)}</strong><br>${esc(c.reason)}</p>`).join('')}${a.timing.map(t=>`<p>${esc(t)}</p>`).join('')}${a.contingency?`<p>Alternative for ${esc(a.contingency.need)}: ${itemButton(a.contingency.name)}<br>${esc(a.contingency.reason)}</p>`:''}<p>Reviewed baseline: ${esc(a.baseline.join(' → ')||'Unavailable')}</p>${a.itemEvidence.issues.map(t=>note(esc(t),true)).join('')}${Object.values(a.itemEvidence.pool).filter(r=>a.slots.some(s=>normalizeName(s.name)===normalizeName(r.name))).map(r=>`<p>${esc(r.name)} · ${pct(r.wr)} · ${games(r.played)}<br>${esc(r.label||r.source)} · ${esc(date(r.fetched_at))} · ${r.supports_current_fit?'Eligible bracket evidence':'Inspection only; no influence'}</p>`).join('')}<p>${esc(a.note)}</p></div></details></section>`;
}
function companionChrome(){
 if(companionMedia.matches){$('#menu-toggle').textContent='More';$('#menu-toggle').removeAttribute('aria-expanded');$('#menu-toggle').setAttribute('aria-controls','main');}
 document.documentElement.classList.toggle('large-text',!!companionPrefs.large);
 let nav=$('#mobile-navigation');if(!nav){nav=document.createElement('nav');nav.id='mobile-navigation';nav.setAttribute('aria-label','Phone navigation');document.body.append(nav);}
 nav.innerHTML=[['meta','Meta'],['builds','Builds'],['planner','Comps'],['draft','Draft'],['live','Live']].map(([r,label])=>`<button data-route="${r}" ${S.route===r||r==='meta'&&S.route==='hero'?'aria-current="page"':''}>${label}</button>`).join('');
 let status=$('#offline-status');if(!status){status=document.createElement('div');status.id='offline-status';status.setAttribute('role','status');$('.workspace').prepend(status);}status.textContent=navigator.onLine?'':'Offline · using saved data. Reconnect to check updates.';status.hidden=navigator.onLine;
 if(B)applyCompanionLink();
 let dock=$('#coach-dock');if(!dock){dock=document.createElement('aside');dock.id='coach-dock';document.body.append(dock);}
 if(nav&&dock.nextElementSibling!==nav)document.body.insertBefore(dock,nav);
 const p=S.route==='live'?S.locks.find(x=>x.slug===S.me):null;
 dock.hidden=!companionMedia.matches||!B||!p;
 if(!dock.hidden){try{const a=adviceFor(p);dock.innerHTML=`<span>${a.available?`Next: <strong>${esc(a.nextPurchase?.name||'Build complete')}</strong>`:'Recommendation unavailable'}</span><button data-edit-situation="${esc(p.slug+'|'+p.role)}">Situation</button>`;}catch{dock.hidden=true;}}

}
function disabledHero(slug,side,role){const own=side==='allies'?S.locks:S.enemies,other=side==='allies'?S.enemies:S.locks;return S.bans.includes(slug)?'Banned':own.some(p=>p.slug===slug&&p.role!==role)||other.some(p=>p.slug===slug)?'Already picked':side==='allies'&&!E.roles(slug).includes(role)?'Role unavailable':'';}
function heroTile(p,{favorite=false}={}){const perf=E.performance(p),review=E.metaReview(p.slug,p.role);return `<article class="mobile-hero-card">${heroButton(p.slug,p.role)}<div class="mobile-stat">${S.bracket==='gold'&&review?tier(review.tier):tier(perf?.tier)} <strong>${pct(perf?.wr)}</strong><small>${games(perf?.played)}</small></div>${favorite?`<button class="favorite-button" data-favorite="${p.slug}|${p.role}" aria-label="Remove ${esc(name(p.slug))} from favorites">★</button>`:''}</article>`;}
function strategyReviewDue(){const g=B?.guidance,m=g?.maintenance_review,next=Date.parse(m?.next_weekly_review);return g?.patch!==B?.official?.live?.version||!!B?.recommendation_context||Number.isFinite(next)&&next<=Date.now();}
function mobileStatusHTML(){const core=latestStatus.health?.core_statistics||{},source=B?.sources?.statz_hero_pages||{},when=core.updated_at||source.fetched_at,age=(Date.now()-Date.parse(when))/3600000,state=!['ok','retained'].includes(source.status)||!Number.isFinite(age)||age<0?'Unavailable':age<=30?'Current':age<=48?'Aging':'Stale';return `<button class="mobile-health ${state.toLowerCase()}" data-route="data"><strong>${esc(state)}</strong><span>Stats updated ${esc(relativeTime(when))}${source.status==='retained'?' · retained':''} · Patch ${esc(B?.official?.status==='verified'?B.official.live?.version:'unverified')}${strategyReviewDue()?' · Strategy review due':''}</span></button>`;}
function relativeTime(value){const ms=Date.now()-Date.parse(value);if(!Number.isFinite(ms))return 'unavailable';const hours=Math.max(0,Math.floor(ms/3600000));return hours<1?'less than 1h ago':hours<24?hours+'h ago':Math.floor(hours/24)+'d ago';}
function guidedHome(){
 const role=roleOrder.includes(S.role)?S.role:'jungle',query=String(companionPrefs.homeQuery||'').toLowerCase();
 const all=Object.keys(E.heroes).filter(slug=>E.roles(slug).includes(role)).map(slug=>({slug,role,perf:E.performance({slug,role})})).filter(r=>r.perf?.played>=100);
 const top=all.slice().sort((a,b)=>{if(S.bracket==='gold'){const order={S:0,A:1,B:2,C:3},ar=E.metaReview(a.slug,role),br=E.metaReview(b.slug,role),d=(order[ar?.tier]??9)-(order[br?.tier]??9);if(d)return d;}return (b.perf.wr??-1)-(a.perf.wr??-1)||(b.perf.played??0)-(a.perf.played??0);}).slice(0,5).map(r=>({slug:r.slug,role}));
 const favorites=companionPrefs.favorites.map(v=>{const [slug,r]=v.split('|');return {slug,role:r};}).filter(p=>E.heroes[p.slug]&&E.roles(p.slug).includes(p.role));
 const recent=companionPrefs.recent.filter(p=>E.heroes[p.slug]&&E.roles(p.slug).includes(p.role)).slice(0,5);
 const matches=query?Object.keys(E.heroes).filter(s=>name(s).toLowerCase().includes(query)&&E.roles(s).includes(role)).sort((a,b)=>name(a).localeCompare(name(b))):[];
 const changes=(B.changes?.vs_previous_run?.changes||[]).filter(c=>c.role===role&&c.matches_from>=100&&c.matches_to>=100&&Math.abs(c.wr_delta)>=.005).sort((a,b)=>Math.abs(b.wr_delta)-Math.abs(a.wr_delta)).slice(0,3);
 return mobileStatusHTML()+(companionError?note(esc(companionError),true):'')+head('Meta · '+esc(B.bracket?.label||''),labels[role]+' at a glance',S.bracket==='gold'?'Reviewed tier guidance leads; current role samples stay visible.':'Selected-rank statistics lead; Gold+ editorial guidance remains separate.')+
 `<div class="role-choices compact" role="tablist" aria-label="Role">${roleOrder.map(r=>`<button role="tab" data-mobile-role="${r}" aria-selected="${role===r}">${labels[r]}</button>`).join('')}</div><label class="mobile-search"><span>Find a ${esc(labels[role].toLowerCase())}</span><input id="mobile-hero-search" type="search" autocomplete="off" placeholder="Hero name" value="${esc(companionPrefs.homeQuery)}"></label>`+
 (query?`<section><h2>Search results</h2><div class="mobile-card-list">${matches.map(slug=>heroTile({slug,role})).join('')||empty('No hero matches this role and search.')}</div></section>`:'')+
 (favorites.length?`<section><h2>Favorites</h2><div class="mobile-card-list">${favorites.map(p=>heroTile(p,{favorite:true})).join('')}</div></section>`:'')+
 (recent.length?`<section><h2>Recent</h2><div class="mobile-card-list">${recent.map(p=>heroTile(p)).join('')}</div></section>`:'')+
 `<section><div class="section-title"><h2>Top five</h2><small>${S.bracket==='gold'?'Reviewed tier, then role performance':'Role performance in '+esc(B.bracket?.label||'selected rank')}</small></div><div class="mobile-card-list">${top.map(p=>heroTile(p)).join('')}</div></section>`+
 `<section><div class="section-title"><h2>What changed</h2><button class="quiet" data-route="changes">All changes</button></div>${changes.length?`<div class="mobile-card-list">${changes.map(c=>`<article class="mobile-change">${heroButton(c.slug,c.role,true)}<strong class="${c.wr_delta>0?'positive':'negative'}">${pp(c.wr_delta)}</strong><small>${num(c.matches_from,0)} → ${num(c.matches_to,0)} games</small></article>`).join('')}</div>`:empty('No qualifying win-rate movement in the available same-rank comparison.')}</section>`;
}
function mobileHero(){
 const p={slug:S.hero,role:S.heroRole};if(!E.heroes[p.slug])return guidedHome();if(!['builds','pairings','counters','kit'].includes(S.heroTab))S.heroTab='builds';
 const blocked=disabledHero(p.slug,'allies',p.role)||(S.locks.some(x=>x.role===p.role&&x.slug!==p.slug)?'This allied role is filled':''),perf=E.performance(p),fav=companionPrefs.favorites.includes(p.slug+'|'+p.role);
 const full=heroView(),node=document.createElement('div');node.innerHTML=full.slice(full.indexOf('<div class="toolbar">'));if(S.heroTab==='builds')node.querySelector('.coach')?.remove();const body=node.innerHTML;
 return `<button class="text-button" data-route="meta">← Meta</button><div class="hero-header mobile-hero-head">${art(p.slug,'large')}<div><h1>${esc(name(p.slug))}</h1><label>Role<select id="mobile-hero-role">${options(E.roles(p.slug).map(r=>[r,labels[r]]),p.role)}</select></label><p>${metaTierButton(p.slug,p.role)} · ${perf?pct(perf.wr)+' · '+games(perf.played):'Role statistics unavailable'}</p></div></div><div class="hero-actions"><button id="favorite-hero" aria-pressed="${fav}">${fav?'★ Favorited':'☆ Favorite'}</button><button id="share-hero">Share</button><button data-start-live="true" ${blocked?'disabled aria-describedby="start-live-reason"':''}>Use in Live</button></div>${blocked?`<p id="start-live-reason">${esc(blocked)}. Clear the conflicting choice in Draft first.</p>`:''}${body}`;
}
function liveMobileDetails(){
 const me=S.locks.find(p=>p.slug===S.me)||null;
 if(!me)return head('Live game','Choose who you play','Add your hero first; the rest of the lineup is optional.')+`<button class="primary" data-live-lookup="true">Choose my hero</button>${S.locks.length?`<label>Or use a locked ally<select id="me-hero">${options(S.locks.map(p=>[p.slug,name(p.slug)+' · '+labels[p.role]]),'','Choose ally')}</select></label>`:''}`;
 const ctx=contextFor(me),owned=Array.isArray(ctx.owned)?ctx.owned:[],all=Object.values(B.items||{}).filter(i=>i.completed_item&&i.available_current_patch!==false&&!owned.includes(i.name)).sort((a,b)=>a.name.localeCompare(b.name));
 return head('Live game',name(me.slug)+' · '+labels[me.role],'Your next completed item and the reason to buy it.')+`<div class="live-actions"><button data-new-match="true">New match</button><button data-live-lookup="true">Change my hero</button></div>${coachHTML(me,{compact:true})}<section class="panel"><h2>Completed items you own</h2><label>Add owned item<select id="live-owned-add" ${owned.length>=6?'disabled aria-describedby="inventory-limit"':''}>${options(all.map(i=>[i.name,i.name]),'','Choose a completed item')}</select></label>${owned.length>=6?'<p id="inventory-limit">All six slots are filled. Remove an incorrect entry to add another.</p>':''}<div class="flex">${owned.map((n,i)=>`<button data-owned-remove="${i}" aria-label="Remove ${esc(n)}">${esc(n)} ×</button>`).join('')||'<p>No completed items entered.</p>'}</div><button id="live-context-clear">Clear inventory & game state</button></section><h2>Lane opponent</h2>${fullSlotRows('enemies',me.role)}<details><summary>Add allies · ${Math.max(0,S.locks.length-1)} selected</summary><div class="detail-content">${fullSlotRows('allies',null,me.role)}</div></details><details><summary>Add enemies · ${S.enemies.filter(e=>e.role!==me.role).length} other roles</summary><div class="detail-content">${fullSlotRows('enemies',null,me.role)}</div></details>`;
}
function liveMobile(){const me=S.locks.find(p=>p.slug===S.me);if(!me)return liveMobileDetails();const node=document.createElement('div');node.innerHTML=liveMobileDetails();const coach=node.querySelector('.coach');coach?.querySelector('.coach-controls')?.remove();if(coach){let next=coach.nextElementSibling;while(next){const old=next;next=next.nextElementSibling;old.remove();}}return node.innerHTML+`<button data-edit-situation="${esc(me.slug+'|'+me.role)}">Edit inventory, threats & lineup</button>`;}
function situationHTML(p){const node=document.createElement('div');node.innerHTML=liveMobileDetails();const controls=node.querySelector('.coach-controls')?.outerHTML||'';const coach=node.querySelector('.coach');const parts=[];let next=coach?.nextElementSibling;while(next){parts.push(next.outerHTML);next=next.nextElementSibling;}return controls+parts.join('');}
function mobileBuilds(){const rows=Object.keys(E.heroes).filter(slug=>E.roles(slug).includes(S.role)&&name(slug).toLowerCase().includes(S.query.toLowerCase())).sort((a,b)=>name(a).localeCompare(name(b)));return head('Builds · '+esc(B.bracket?.label||''),'Reviewed starting plans','Choose a role, then open one compact plan. Source variants remain on the hero page.')+metaToolbarHTML()+maintenanceHTML()+`<div class="mobile-build-list">${rows.map(slug=>{const plan=E.plannedBuild(slug,S.role),perf=E.performance({slug,role:S.role});return `<details class="panel mobile-build-row"><summary>${art(slug,'tiny')}<span><strong>${esc(name(slug))}</strong><small>${perf?pct(perf.wr)+' · '+games(perf.played):'Role sample unavailable'}</small></span><span>${plan.kind==='reviewed'?badge('Reviewed','reviewed'):badge('Provisional','warning')}</span></summary><div class="detail-content">${plannedBuildHTML(plan,true)}<button data-hero-builds="${slug}" data-role="${S.role}">Open full build</button></div></details>`;}).join('')}</div>${!rows.length?empty('No heroes match this role and search.'):''}`;}
function compactResults(node,selector){const cards=[...node.querySelectorAll(selector)];if(cards.length>3){const extra=document.createElement('details');extra.innerHTML='<summary>More suggestions</summary><div class="detail-content grid"></div>';cards[2].after(extra);cards.slice(3).forEach(c=>extra.lastElementChild.append(c));}}
function mobilePlanner(){const node=document.createElement('div');node.innerHTML=plannerView();compactResults(node,'#compositions > .grid > article');return `<div class="mobile-focused planner-focused">${node.innerHTML}</div>`;}
function mobileDraft(){const node=document.createElement('div');node.innerHTML=draftView();const toolbar=node.querySelector('#candidate-role')?.closest('.toolbar');if(toolbar)node.querySelector('.page-head').after(toolbar);const allSlots=[...node.querySelectorAll('.slots')];for(const slot of allSlots){const detail=document.createElement('details');detail.innerHTML='<summary>Edit lineup</summary><div class="detail-content"></div>';slot.replaceWith(detail);detail.lastElementChild.append(slot);}compactResults(node,':scope > .grid.three > article');return `<div class="mobile-focused draft-focused">${node.innerHTML}</div>`;}
function moreView(){return head('All tools','More','Planning, evidence and preferences.')+`<div class="more-grid">${[['planner','Compositions'],['library','Items & loadouts'],['guidance','Reviewed guide'],['changes','Changes'],['data','Sources & accuracy']].map(([r,t])=>`<button data-route="${r}">${t}</button>`).join('')}<button id="download-review-packet">Download strategy review packet</button><button id="companion-install">Install / offline help</button><button id="companion-theme">Switch to ${document.documentElement.dataset.theme==='light'?'dark':'light'} theme</button><button id="share-plan">Share draft plan</button><button id="import-plan">Open draft plan</button><button id="export">Export snapshot</button></div><section class="panel"><h2>Reading preferences</h2><label><input id="large-text" type="checkbox" ${companionPrefs.large?'checked':''}> Large text</label><p>Phone text scaling and reduced motion settings are respected.</p><button data-new-match="true">New match</button><p>Keeps planning picks and preferences; resets inventory and live judgments.</p></section>`;}
function downloadReviewPacket(){const packet={schema:1,generated_at:new Date().toISOString(),tool_version:APP_CONFIG.tool_version,live_patch:B.official?.live,statistics:{bracket:B.bracket,source_dates:B.sources,changes:B.changes},guidance:{patch:B.guidance?.patch,status:B.guidance?.status,reviewed_at:B.guidance?.reviewed_at,next_review_at:B.guidance?.maintenance_review?.next_weekly_review,due:strategyReviewDue()},plans:(B.guidance?.builds||[]).map(p=>({slug:p.slug,role:p.role,result:p.maintenance_review?.result||'unresolved',reviewed_at:p.maintenance_review?.reviewed_at||p.reviewed_at,reason:p.maintenance_review?.reason||'No maintenance result recorded',limitation:p.maintenance_review?.limitation||''})),official_changes:B.official?.changes||[],definition_conflicts:B.definition_issues||[]};const blob=new Blob([JSON.stringify(packet,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Predecessor-strategy-review-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function renderCompanion(){
 if(!B){if(companionMedia.matches){$('#main').innerHTML=latestStatus.errors?.length?`<h1>Data unavailable</h1><p>${esc(latestStatus.errors[0].detail)}</p><button id="retry-companion">Retry update</button><p>Choose another rank above to inspect available data.</p>`:`<h1>Loading hero data</h1><p role="status">Your selections are safe. Opening ${esc(S.bracket)}…</p><div class="loading-skeleton" aria-hidden="true"></div>`;return true;}return false;}
 if(S.route==='more'){$('#main').innerHTML=moreView();return true;}
 if(!companionMedia.matches)return false;
 if(S.route==='meta'){$('#main').innerHTML=guidedHome();return true;}
 if(S.route==='hero'){$('#main').innerHTML=mobileHero();return true;}
 if(S.route==='builds'){$('#main').innerHTML=mobileBuilds();return true;}
 if(S.route==='planner'){$('#main').innerHTML=mobilePlanner();return true;}
 if(S.route==='draft'){$('#main').innerHTML=mobileDraft();return true;}
 if(S.route==='live'){$('#main').innerHTML=liveMobile();return true;}
 return false;
}
// Guard the same role controls on both layouts; invalid options explain the conflict.
function fullSlotRows(side,onlyRole=null,exceptRole=null){const picks=side==='allies'?S.locks:S.enemies;return `<div class="slots">${roleOrder.filter(r=>(!onlyRole||r===onlyRole)&&r!==exceptRole).map(r=>{const current=picks.find(p=>p.role===r);return `<div class="slot"><label>${labels[r]}<select data-slot="${side}" data-slot-role="${r}" aria-describedby="${side}-${r}-help"><option value="">Open slot</option>${Object.keys(E.heroes).sort((a,b)=>name(a).localeCompare(name(b))).map(s=>{const reason=disabledHero(s,side,r);return `<option value="${s}" ${current?.slug===s?'selected':''} ${reason?'disabled':''}>${esc(name(s))}${reason?' — '+esc(reason):''}</option>`;}).join('')}</select></label><small id="${side}-${r}-help">Picked, banned or unsupported-role choices are disabled.</small>${current?`<div class="slot-art">${art(current.slug,'tiny')}${esc(name(current.slug))}</div>`:''}</div>`;}).join('')}</div>`;}
slotRows=function(side){if(!companionMedia.matches)return fullSlotRows(side);const role=S.locks.find(p=>p.slug===S.me)?.role||S.role;return fullSlotRows(side,role)+`<details><summary>Add ${side==='allies'?'allies':'enemies'} · other roles</summary><div class="detail-content">${fullSlotRows(side,null,role)}</div></details>`;};
const originalChangeRoute=changeRoute,originalOpenHero=openHero;
const originalDetail=detail;let dialogReturn=null,dialogSituation=null;
detail=function(title,body){dialogReturn=document.activeElement;dialogSituation=dialogReturn?.dataset?.editSituation;originalDetail(title,body);};
$('#detail').addEventListener('close',()=>{if(dialogReturn?.isConnected)dialogReturn.focus();else if(dialogSituation)document.querySelector('[data-edit-situation]')?.focus();else $('#main').focus({preventScroll:true});});
changeRoute=function(route){originalChangeRoute(route);recordNavigation();};
openHero=function(slug,role){if(!E.heroes[slug]){companionError='That hero is unavailable. Choose another.';changeRoute('meta');return;}originalOpenHero(slug,role);companionPrefs.recent=[{slug,role:S.heroRole},...companionPrefs.recent.filter(p=>p.slug!==slug||p.role!==S.heroRole)].slice(0,5);saveCompanionPrefs();recordNavigation(true);};
function navigationState(){return {route:S.route,hero:S.hero,role:S.heroRole,tab:S.heroTab,bracket:S.bracket};}
function recordNavigation(replace=false){if(historyApplying||location.protocol==='file:')return;const n=navigationState();const url=new URL(location.href);if(n.route==='hero'&&n.hero)url.hash='hero='+encodeURIComponent(n.hero)+'&role='+n.role+'&bracket='+n.bracket+'&tab='+n.tab;else url.hash='view='+n.route;if(history.state?.companion&&JSON.stringify(history.state.companion)===JSON.stringify(n))return;history[replace?'replaceState':'pushState']({companion:n},'',url);linkApplied=url.hash;}
function applyCompanionLink(){
 const hash=location.hash;if(!hash||hash.startsWith('#plan=')||hash===linkApplied)return;linkApplied=hash;
 try{const q=new URLSearchParams(hash.slice(1));if(q.has('hero')){
   const allowed=['hero','role','bracket','tab'];if([...q.keys()].some(k=>!allowed.includes(k))||[...q.keys()].length!==new Set(q.keys()).size)throw Error('The hero link has unsupported fields.');
   const hero=q.get('hero'),role=q.get('role'),bracket=q.get('bracket'),tab=q.get('tab')||'builds';
   if(!E.heroes[hero])throw Error('The linked hero is unavailable. Choose a hero.');
   if(!roleOrder.includes(role)||!E.roles(hero).includes(role)){throw Error('Choose a supported role for the linked hero.');}
   if(!['bronze','silver','gold','platinum','diamond','paragon'].includes(bracket)||!['builds','pairings','counters','kit'].includes(tab))throw Error('The linked rank or section is invalid.');
   if(bracket!==S.bracket){linkApplied='';queueMicrotask(()=>{const select=$('#bracket');select.value=bracket;select.dispatchEvent(new Event('change',{bubbles:true}));});return;}
   S.hero=hero;S.heroRole=role;S.heroTab=tab;S.route='hero';
 }else if(q.has('view')){const r=q.get('view');if(![...navs.map(x=>x[0]),'more'].includes(r))throw Error('This section is unavailable.');S.route=r;}
 }catch(e){companionError=e.message;S.route='meta';}
}
function undoSnapshot(){return copyValue({locks:S.locks,enemies:S.enemies,bans:S.bans,me:S.me,liveVariant:S.liveVariant,contexts:S.liveContexts});}
function showUndo(before,label){clearTimeout(undoTimer);undoAction=before;let el=$('#undo-banner');if(!el){el=document.createElement('div');el.id='undo-banner';el.setAttribute('role','status');document.body.append(el);el.addEventListener('focusin',()=>clearTimeout(undoTimer));el.addEventListener('mouseenter',()=>clearTimeout(undoTimer));el.addEventListener('mouseleave',expireUndo);el.addEventListener('focusout',expireUndo);}el.hidden=false;el.innerHTML=`<span>${esc(label)}</span><button id="undo-action">Undo</button>`;expireUndo();}
function expireUndo(){clearTimeout(undoTimer);undoTimer=setTimeout(()=>{if($('#undo-banner')?.contains(document.activeElement))return;undoAction=null;if($('#undo-banner'))$('#undo-banner').hidden=true;},8000);}
function installHelp(){companionPrefs.installSeen=true;saveCompanionPrefs();document.querySelector('.install-hint')?.remove();detail('Install on your phone','<p><strong>iPhone / iPad:</strong> open this website in Safari, tap Share, then Add to Home Screen.</p><p><strong>Android:</strong> open in Chrome, use its menu and choose Install app or Add to Home screen.</p><p>Open a rank online once to save it on this device. Offline views retain their original dates. Images may be unavailable offline.</p>');}
async function shareHero(){const url=new URL(APP_CONFIG.mode==='local'||location.protocol==='file:'?'https://gn45db4tjc-ship-it.github.io/predecessor-meta/':location.href);url.search='';url.hash='hero='+encodeURIComponent(S.hero)+'&role='+S.heroRole+'&bracket='+S.bracket+'&tab='+S.heroTab;try{if(navigator.share){await navigator.share({title:name(S.hero)+' build',url:url.href});return;}}catch(e){if(e.name==='AbortError')return;}try{await navigator.clipboard.writeText(url.href);toast('Hero link copied.');}catch{detail('Share hero',`<label>Copy this link<input readonly value="${esc(url.href)}"></label><p>Contains only hero, role, bracket and section.</p>`);}}
document.addEventListener('click',async event=>{
 const el=event.target.closest('button');if(!el)return;const d=el.dataset;
 if(d.ownedRemove!==undefined||['live-context-clear','clear-locks','clear-enemies'].includes(el.id)||d.unban){const before=undoSnapshot();setTimeout(()=>showUndo(before,'Selection cleared.'),0);}
 const handled=d.mobileRole||d.favorite||d.liveLookup||d.startLive||d.newMatch||d.editSituation||['menu-toggle','undo-action','companion-install','companion-theme','share-hero','favorite-hero','download-review-packet','live-context-clear','retry-companion'].includes(el.id);
 if(!handled)return;event.preventDefault();event.stopImmediatePropagation();
 try{
 if(el.id==='menu-toggle'){changeRoute('more');return;}
 if(el.id==='retry-companion'){$('#refresh').click();return;}
 if(el.id==='download-review-packet'){downloadReviewPacket();return;}
 if(d.editSituation){const [slug,role]=d.editSituation.split('|');detail('Your game situation',situationHTML({slug,role}));return;}
 if(el.id==='live-context-clear'){S.liveContexts[liveContextKey()]={owned:[],state:'even',priority:''};}
 else if(d.mobileRole){S.role=d.mobileRole;companionPrefs.homeQuery='';saveCompanionPrefs();}
 else if(d.favorite){companionPrefs.favorites=companionPrefs.favorites.filter(v=>v!==d.favorite);saveCompanionPrefs();}
 else if(el.id==='favorite-hero'){const key=S.hero+'|'+S.heroRole;companionPrefs.favorites=companionPrefs.favorites.includes(key)?companionPrefs.favorites.filter(v=>v!==key):[key,...companionPrefs.favorites].slice(0,20);saveCompanionPrefs();}
 else if(d.liveLookup){S.route='meta';companionPrefs.homeQuery='';}
 else if(d.startLive){const reason=disabledHero(S.hero,'allies',S.heroRole);if(reason)throw Error(reason+'. Clear the conflicting pick or ban in Draft first.');const occupied=S.locks.find(p=>p.role===S.heroRole&&p.slug!==S.hero);if(occupied)throw Error('This role belongs to '+name(occupied.slug)+'. Clear it in Draft first.');setPick('allies',S.heroRole,S.hero);S.me=S.hero;S.route='live';}
 else if(d.newMatch){const before=undoSnapshot();S.liveContexts={};S.liveVariant=null;showUndo(before,'New match: inventory and live judgments reset. Planning picks kept.');}
 else if(el.id==='undo-action'&&undoAction){const before=undoAction;S.locks=before.locks;S.enemies=before.enemies;S.bans=before.bans;S.me=before.me;S.liveVariant=before.liveVariant;S.liveContexts=before.contexts;undoAction=null;clearTimeout(undoTimer);$('#undo-banner').hidden=true;}
 else if(el.id==='companion-install'){installHelp();return;}
 else if(el.id==='companion-theme'){$('#theme-toggle').click();}
 else if(el.id==='share-hero'){await shareHero();return;}
 save();render();recordNavigation();$('#main').focus({preventScroll:true});
 }catch(e){companionError=e.message;toast(e.message);}
},true);
document.addEventListener('change',event=>{
 const el=event.target,d=el.dataset;
 if(d.slot&&el.value){const why=disabledHero(el.value,d.slot,d.slotRole);if(why){event.stopImmediatePropagation();toast(why+'. Clear the existing selection first.');render();return;}}
 if(d.slot&&!el.value){const before=undoSnapshot();setTimeout(()=>showUndo(before,'Pick removed.'),0);}
 if(d.coachField){event.stopImmediatePropagation();const [slug,role]=d.coachKey.split('|'),p={slug,role};if(!E.heroes[slug]||!E.roles(slug).includes(role))return;const val=d.coachField==='primaryThreat'?(el.value||null):el.value;S.liveContexts[d.coachKey]={...contextFor(p),[d.coachField]:val};const modal=$('#detail').open;save();render();if(!modal)document.querySelector(`[data-coach-key="${d.coachKey}"][data-coach-field="${d.coachField}"]`)?.focus();}
 else if(el.id==='mobile-hero-role'){S.heroRole=el.value;render();recordNavigation(true);$('#mobile-hero-role')?.focus();}
 else if(el.id==='large-text'){companionPrefs.large=el.checked;saveCompanionPrefs();companionChrome();}
 else if(el.id==='hero-role')setTimeout(()=>recordNavigation(true),0);
},true);
document.addEventListener('input',event=>{if(event.target.id==='mobile-hero-search'){const pos=event.target.selectionStart;companionPrefs.homeQuery=event.target.value;saveCompanionPrefs();render();const input=$('#mobile-hero-search');input?.focus();input?.setSelectionRange(pos,pos);}});
document.addEventListener('click',event=>{if(event.target.closest('[data-hero-tab]')){recordNavigation(true);if(companionMedia.matches){const d=$('#main > details');if(d)d.open=true;}}});
window.addEventListener('popstate',event=>{historyApplying=true;if(event.state?.companion){const n=event.state.companion;S.route=n.route;S.hero=n.hero;S.heroRole=n.role;S.heroTab=n.tab;}linkApplied='';render();historyApplying=false;});
window.addEventListener('hashchange',()=>{if(!location.hash.startsWith('#plan=')){linkApplied='';render();}});
window.addEventListener('offline',()=>{render();});window.addEventListener('online',()=>{render();});
companionMedia.addEventListener('change',()=>render());
function refreshSituation(event){if(!$('#detail')?.open||$('#detail-title').textContent!=='Your game situation')return;if(!event.target.closest('#detail-body'))return;const id=event.target.id,key=event.target.dataset.coachField;setTimeout(()=>{const me=S.locks.find(p=>p.slug===S.me);if(!me)return;$('#detail-body').innerHTML=situationHTML(me);(id?$('#detail-body #'+id):key?$('#detail-body [data-coach-field="'+key+'"]'):null)?.focus();},0);}
document.addEventListener('change',refreshSituation,true);
document.addEventListener('click',event=>{if(event.target.closest('[data-owned-remove],#live-context-clear'))refreshSituation(event);},true);
setTimeout(()=>{if(companionMedia.matches&&!companionPrefs.installSeen&&APP_CONFIG.mode==='static'&&!matchMedia('(display-mode:standalone)').matches){let el=document.createElement('aside');el.className='install-hint';el.innerHTML='<span>Add this companion to your home screen.</span><button id="companion-install">How to install</button><button aria-label="Dismiss installation hint">Dismiss</button>';el.lastElementChild.onclick=()=>{companionPrefs.installSeen=true;saveCompanionPrefs();el.remove();};$('#main').after(el);}},1200);
