'use strict';
// Two independently rendered releases, one browser profile, then a real server outage.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const engine=process.env.BROWSER_ENGINE||'edge',oldRoot=path.resolve(process.env.PREVIOUS_SITE||'qa/baseline-2291/qa/audit-site'),nextRoot=path.resolve(process.env.NEXT_SITE||'qa/companion-site');
let serving=oldRoot,down=false;
const server=http.createServer((q,r)=>{if(down){q.socket.destroy();return;}const name=decodeURIComponent(new URL(q.url,'http://localhost').pathname).replace(/^\/+/, '')||'index.html',file=path.resolve(serving,name);if(!file.startsWith(serving+path.sep)||!fs.existsSync(file)){r.writeHead(404);r.end();return;}r.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'})[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});r.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/',browser=await(engine==='webkit'?webkit.launch():chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge'}));
try{const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const ready=()=>page.waitForFunction(()=>!!B&&!latestStatus.busy,null,{timeout:60000});await page.goto(url);await ready();await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await ready();
const before=await page.evaluate(()=>{S.locks=[{slug:'khaimera',role:'jungle'}];S.me='khaimera';save();return B.generated_at;});assert.equal(await page.evaluate(()=>typeof CompanionState),'undefined');
serving=nextRoot;await page.reload();await ready();await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});
for(let i=0;;i++){if(await page.evaluate(async()=>{const k=await caches.keys();return k.includes('predecessor-meta-shell-v2-30-0')&&!k.includes('predecessor-meta-shell-v2-29-0');}))break;if(i===150)throw Error('New worker did not activate');await new Promise(r=>setTimeout(r,200));}
await page.reload();await ready();assert.equal(await page.evaluate(()=>typeof CompanionState),'object');await page.evaluate(()=>changeRoute('live'));down=true;await page.reload();await ready();
assert.equal(await page.evaluate(()=>typeof CompanionState),'object');assert.equal(await page.evaluate(()=>B.generated_at),before);assert.equal(await page.evaluate(()=>S.me),'khaimera');assert.deepEqual(await page.locator('#mobile-navigation button').allTextContents(),['Meta','Plan','More']);assert.deepEqual(errors,[]);
fs.writeFileSync(`qa/release-upgrade-${engine}.json`,JSON.stringify({engine,from:'2.29.1',to:'2.30.0',workerActivated:true,newShellOpenedOffline:true,picksPreserved:true,sourceDatePreserved:before,errors},null,2));console.log('Actual 2.29.1 to 2.30.0 upgrade: offline shell, picks and source date preserved.');await context.close();
}finally{await browser.close();server.close();server.closeAllConnections();}})().catch(e=>{console.error(e);server.close();server.closeAllConnections();process.exitCode=1;});
