'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const axe=process.env.AXE_PATH||require('node:path').resolve('qa/a11y/node_modules/axe-core/axe.min.js');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),report=[];try{
 for(const theme of ['dark','light']){const c=await b.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),p=await c.newPage();await c.addInitScript(t=>{localStorage.setItem('predecessor-companion-v1',JSON.stringify({installSeen:true}));localStorage.setItem('predecessor-theme',t)},theme);await p.goto(process.env.PREVIEW_URL||'http://127.0.0.1:12932');await p.waitForFunction(()=>!!B&&!latestStatus.busy);await p.addScriptTag({path:axe});
 for(const route of ['meta','hero','live','more','builds','draft','planner','data','library','guidance','changes']){await p.evaluate(r=>{S.locks=[{slug:'steel',role:'jungle'}];S.enemies=[{slug:'khaimera',role:'jungle'}];S.me='steel';if(r==='hero'){S.hero='steel';S.heroRole='jungle';}changeRoute(r)},route);const r=await p.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));report.push({theme,route,violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary})).slice(0,8)}))});}
 const states=[['meta-name-order',async()=>{await p.evaluate(()=>changeRoute('meta'));await p.selectOption('#mobile-meta-order','name');}],['live-hero-picker',async()=>{await p.evaluate(()=>changeRoute('live'));await p.locator('[data-live-lookup]').first().click();}],['live-replace-preview',async()=>{await p.locator('#detail [data-pick-live]:not([disabled])').first().click();}],['source-limitations',async()=>{await p.keyboard.press('Escape');await p.evaluate(()=>{B.errors=[...(B.errors||[]),{source:'Accessibility probe',severity:'warning',detail:'A source note for the accessibility check.'}];changeRoute('meta');});await p.locator('#mobile-limits').click();}]];
 for(const [route,open] of states){await open();const r=await p.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));report.push({theme,route,violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary})).slice(0,8)}))});}
 await p.keyboard.press('Escape');
 await p.evaluate(()=>changeRoute('more'));await p.locator('#large-text').check();await p.evaluate(()=>changeRoute('live'));await p.locator('[data-edit-situation]').first().click();await p.locator('#detail [data-coach-field="state"]').selectOption('behind');await p.keyboard.press('Escape');assert.ok(!(await p.locator('#detail').isVisible()));await p.keyboard.press('Tab');assert.ok(await p.evaluate(()=>document.activeElement!==document.body));
 await p.setViewportSize({width:320,height:800});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'large text 320px');await c.close();
 }
 }finally{await b.close();fs.writeFileSync('qa/companion-accessibility.json',JSON.stringify(report,null,2));}console.log(JSON.stringify(report.filter(x=>x.violations.length),null,2));assert.ok(report.every(r=>!r.violations.length),'WCAG automated checks');})().catch(e=>{console.error(e);process.exit(1)});
