'use strict';
const {goToScreen}=require('./navigation_helpers.cjs');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const url=process.env.PREVIEW_URL||'http://127.0.0.1:12932/',report={checks:[],screens:[],errors:[]};
const check=(v,label)=>{assert.ok(v,label);report.checks.push(label);};
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(()=>localStorage.setItem('predecessor-companion-v1',JSON.stringify({installSeen:true})));
 const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));const start=Date.now();await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!B&&!latestStatus.busy);report.readyMs=Date.now()-start;
 check(!(await page.locator('#main').innerText()).includes('Opponent'),'mobile Meta home has no opponent step');
 check(await page.locator('.mobile-card-list').count()>0,'mobile Meta home shows focused cards');
 await page.locator('#menu-toggle').click();check(await page.locator('#large-text').isVisible(),'More is reachable from the header');await page.locator('#mobile-navigation [data-route="meta"]').click();await page.screenshot({path:'qa/mobile-meta-390.png',fullPage:true});
 await page.locator('#mobile-hero-search').fill('Steel');await page.locator('[data-hero="steel"]').first().click();
 check(await page.evaluate(()=>S.heroTab==='builds'),'hero opens on Build');check(await page.locator('#main .build-path').count()>0,'mobile hero leads with the reviewed build');
 await page.locator('#favorite-hero').click();check(await page.locator('#favorite-hero').getAttribute('aria-pressed')==='true','favorite is stored');
 await page.locator('[data-start-live]').click();check(await page.evaluate(()=>S.route==='live'&&S.me==='steel'),'one tap transfers selected hero into Live');
 await page.locator('[data-edit-situation]').first().click();await page.locator('[data-coach-field="state"]').selectOption('behind');await page.locator('[data-coach-field="priority"]').selectOption('anti_heal');
 const baseline=await page.evaluate(()=>JSON.stringify({pairs:B.pairs,tier:B.tier_list}));
 const first=await page.evaluate(()=>E.adaptBuild({slug:'steel',role:'jungle'},S.locks,S.enemies).baseline[0]);await page.selectOption('#live-owned-add',first);
 check(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('predecessor-match-v2')).contexts['steel|jungle'].owned.length===1),'match context stored in session');
 check(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('predecessor-planner-v2')).liveContexts).length===0),'inventory excluded from persistent planner');
 await page.reload();await page.waitForFunction(()=>!!B&&!latestStatus.busy);await goToScreen(page,'live');await page.locator('[data-edit-situation]').first().click();check(await page.locator('[data-owned-remove]').count()===1,'session reload restores inventory');
 await page.locator('[data-owned-remove]').click();await page.keyboard.press('Escape');await page.locator('#undo-action').click();await page.locator('[data-edit-situation]').first().click();check(await page.locator('[data-owned-remove]').count()===1,'Undo restores removed item');await page.keyboard.press('Escape');
 await page.locator('[data-new-match]').first().click();check(await page.evaluate(()=>!contextFor({slug:'steel',role:'jungle'}).owned.length),'New match clears inventory');check(await page.evaluate(()=>contextFor({slug:'steel',role:'jungle'}).state==='even'),'New match resets personal state');await page.locator('#undo-action').click();check(await page.evaluate(()=>contextFor({slug:'steel',role:'jungle'}).owned.length===1),'Undo restores complete game context');
 for(const width of [320,375,390,412,844,1080,1440]){await page.setViewportSize({width,height:width===844?390:900});await page.evaluate(()=>render());await page.screenshot({path:`qa/companion-${width}.png`,fullPage:true});report.screens.push(width);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no page overflow at '+width);}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>changeRoute('more'));await page.locator('#large-text').check();await page.locator('#companion-theme').click();check(await page.evaluate(()=>document.documentElement.dataset.theme==='light'),'light theme');await goToScreen(page,'live');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'large text phone reflow');await page.screenshot({path:'qa/companion-large-light.png',fullPage:true});
 for(const route of ['meta','builds','draft','live','more','planner','library','guidance','changes','data']){await page.evaluate(r=>changeRoute(r),route);check(!(await page.locator('#main').innerText()).includes('could not render'),'route '+route+' renders');}
 await page.evaluate(()=>openHero('steel','jungle'));await page.evaluate(()=>{B.official.status='failed';E=MetaEngine.create(B);render();});check((await page.locator('#main').innerText()).includes('unavailable'),'failed verification has explicit unavailable state');
 await page.reload();await page.waitForFunction(()=>!!B&&!latestStatus.busy);
 for(const bracket of ['bronze','silver','gold','platinum','diamond','paragon']){await page.selectOption('#bracket',bracket);await page.waitForFunction(b=>B?.bracket?.segment===b&&!latestStatus.busy,bracket);check(await page.evaluate(()=>S.bracket===B.bracket.segment),'rank '+bracket+' stays separate');}
 await page.goto(url+'#hero=steel&role=jungle&bracket=gold&tab=builds');await page.waitForFunction(()=>B?.bracket?.segment==='gold'&&S.route==='hero'&&!latestStatus.busy);check(await page.evaluate(()=>S.hero==='steel'&&S.heroRole==='jungle'),'hero deep link restores rank and role');
 await page.evaluate(()=>changeRoute('more'));await page.goBack();check(await page.evaluate(()=>S.route==='hero'),'browser Back restores hero');
 await page.goto(url+'#hero=unknown&role=jungle&bracket=gold&tab=builds');await page.waitForFunction(()=>!!B&&!latestStatus.busy);check((await page.locator('#main').innerText()).includes('unavailable'),'invalid link has recoverable explanation');
 check(report.errors.length===0,'no browser exceptions');
 await context.close();const offline=await browser.newContext({viewport:{width:390,height:844}}),p=await offline.newPage();await p.goto(url);await p.waitForFunction(()=>!!B&&!latestStatus.busy);await p.evaluate(()=>navigator.serviceWorker.ready);await p.reload();await p.waitForFunction(()=>!!B&&!latestStatus.busy&&!!navigator.serviceWorker.controller);const at=await p.evaluate(()=>B.generated_at);await offline.setOffline(true);await p.reload();await p.waitForFunction(()=>!!B&&!latestStatus.busy);check(await p.evaluate(()=>B.generated_at)===at,'offline keeps original bundle date');check(await p.locator('#offline-status').isVisible(),'offline warning visible');await offline.close();
 }finally{await browser.close();fs.writeFileSync('qa/companion-verification.json',JSON.stringify(report,null,2));}console.log(JSON.stringify(report,null,2));})().catch(e=>{console.error(e);process.exit(1)});
