'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict'),fs=require('fs');
const url=process.env.PREVIEW_URL||'http://127.0.0.1:12932/';
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),checks=[];try{const c=await b.newContext({viewport:{width:1920,height:1080},acceptDownloads:true,serviceWorkers:'block'}),p=await c.newPage();await p.goto(url);await p.waitForFunction(()=>!!B&&!latestStatus.busy);const original=await p.evaluate(()=>JSON.stringify({at:B.generated_at,tiers:B.tier_list,pairs:B.pairs}));
 // With no eligible statistics source (e.g. a new patch), sampled search withholds suggestions; the kit search must still honour the constraints.
 const comp=await p.evaluate(()=>{const sampled=E.evidenceState().statistics.state!=='unavailable',out=[];for(const size of [2,3,5]){const locks=[{slug:'steel',role:'jungle'}],bans=['khaimera'],enemies=[{slug:'gideon',role:'midlane'}];const r=E.generate(locks,{size,bans,enemies,width:10,includeUnsampled:!sampled});out.push({size,sampled,withheld:sampled||E.generate(locks,{size,bans,enemies,width:10}).alternatives.length===0,count:r.alternatives.length,valid:r.alternatives.every(c=>c.picks.length===size&&new Set(c.picks.map(p=>p.role)).size===size&&new Set(c.picks.map(p=>p.slug)).size===size&&c.picks.some(p=>p.slug==='steel'&&p.role==='jungle')&&c.picks.every(p=>!['khaimera','gideon'].includes(p.slug)))})}return out});assert(comp.every(r=>r.count>0&&r.valid&&r.withheld),JSON.stringify(comp));checks.push('2/3/5 suggestions preserve locks, roles and bans'+(comp[0].sampled?'':' (kit search; sampled search withheld without a statistics source)'));
 await p.evaluate(()=>{S.locks=[{slug:'steel',role:'jungle'},{slug:'gideon',role:'midlane'}];S.enemies=[];S.bans=[];S.me='steel';S.liveContexts={'steel|jungle':{owned:['Fire Blossom'],state:'behind',priority:''}};save();sharePlan();});const link=await p.locator('#plan-link').inputValue();assert(!link.includes('Fire'));await p.locator('#close-detail').click();
 const visitor=await b.newContext(),v=await visitor.newPage();await v.goto(link);await v.waitForSelector('#use-shared-plan');assert.equal(await v.evaluate(()=>S.locks.length),0);await v.locator('#use-shared-plan').click();assert.equal(await v.evaluate(()=>S.locks.length),2);await visitor.close();checks.push('shared draft preview and import exclude inventory');
 const down=p.waitForEvent('download');await p.locator('#export').click();const path='qa/222-export.html';await(await down).saveAs(path);const e=await c.newPage();await e.goto('file:///'+require('path').resolve(path).replaceAll('\\','/'));assert.equal(await e.evaluate(()=>APP_CONFIG.mode),'export');assert.equal(await e.evaluate(()=>JSON.stringify({at:B.generated_at,tiers:B.tier_list,pairs:B.pairs})),original);await e.close();checks.push('standalone export preserves exact observations and loads companion code');
 for(const viewport of [{width:1920,height:1080,scale:1},{width:2560,height:1440,scale:1},{width:1536,height:864,scale:1.25}]){await p.setViewportSize({width:viewport.width,height:viewport.height});for(const r of ['meta','builds','draft','live','planner','library','guidance','changes','data']){await p.evaluate(r=>changeRoute(r),r);assert.ok(!(await p.locator('#main').innerText()).includes('could not render'));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}checks.push('desktop routes at '+viewport.width+'x'+viewport.height);}
 await p.route('**/manifest.json',r=>r.abort());await p.locator('#refresh').click();await p.waitForFunction(()=>!latestStatus.busy);assert.ok(await p.evaluate(()=>B&&latestStatus.errors.length));await p.unroute('**/manifest.json');checks.push('publication failure retains labelled data');
 await p.route('**/manifest.json',async r=>{const response=await r.fetch(),m=await response.json();m.cohorts.diamond={label:'Diamond+',status:'unavailable'};await r.fulfill({response,json:m});});await p.selectOption('#bracket','diamond');await p.waitForFunction(()=>!latestStatus.busy);assert.equal(await p.evaluate(()=>B),null);assert.match(await p.locator('#main').innerText(),/No successful diamond publication/);checks.push('unavailable rank never substitutes Gold');await c.close();
 }finally{await b.close();fs.writeFileSync('qa/release-222-browser.json',JSON.stringify({checks},null,2));}console.log(checks.join('\n'));})().catch(e=>{console.error(e);process.exit(1)});
