const test=require('node:test'),assert=require('node:assert/strict'),zlib=require('node:zlib'),fs=require('node:fs');
const M=require('../engine.js'),C=require('../companion_state.js'),K=require('../skill_guide.js');
const seed=()=>JSON.parse(zlib.gunzipSync(fs.readFileSync(require('node:path').join(__dirname,'../public-seed-gold.json.gz'))));
function selection(){const b=seed(),e=M.create(b),slug=Object.keys(b.heroes).find(s=>b.heroes[s].roles?.jungle?.builds?.length>1),role='jungle',ref=C.reference(b,e,slug,role,0);return {b,e,slug,role,ref};}
test('selected playstyle resolves after source variant reorder and statistics-only publication update',()=>{const {b,slug,role,ref}=selection();b.heroes[slug].roles[role].builds.reverse();b.generated_at='2026-09-23T12:00:00Z';const out=C.resolve(b,M.create(b),ref,slug,role);assert.equal(out.status,'selected');assert.equal(out.revalidated,true);assert.notEqual(out.index,0);});
test('selected playstyle invalidates separately for patch, rank, recipe and mechanics changes',()=>{for(const change of ['patch','rank','recipe','mechanics']){const {b,slug,role,ref}=selection();if(change==='patch')b.official.live.version='9.0';if(change==='rank')b.bracket.segment='diamond';if(change==='recipe')b.heroes[slug].roles[role].builds=[];if(change==='mechanics')b.heroes[slug].abilities[0].text+=' changed';assert.equal(C.resolve(b,M.create(b),ref,slug,role).status,'invalid',change);}});
test('malformed and cross-hero selections cannot silently resolve',()=>{const {b,e,ref,slug,role}=selection();assert.throws(()=>C.reference(b,e,slug,role,-1));assert.equal(C.resolve(b,e,{...ref,v:99},slug,role).status,'invalid');assert.equal(C.resolve(b,e,ref,'muriel','support').status,'invalid');});
test('quick draft validation rejects hero, role and ban conflicts even before list regeneration',()=>{const engine={roles:()=>['jungle']},p={allies:[],enemies:[],bans:[]};assert.equal(C.blocked('steel','jungle',p,engine),'');p.bans=['steel'];assert.equal(C.blocked('steel','jungle',p,engine),'Banned');p.bans=[];p.enemies=[{slug:'steel',role:'offlane'}];assert.equal(C.blocked('steel','jungle',p,engine),'Enemy pick');p.enemies=[];p.allies=[{slug:'khaimera',role:'jungle'}];assert.equal(C.blocked('steel','jungle',p,engine),'Ally or role already locked');});
test('skill orders never turn calculated priorities into reviewed allocations',()=>{const {b,e,slug,role}=selection(),plan=e.plannedBuild(slug,role);const result=K.make(b,plan);assert.notEqual(result.kind,'reviewed');if(result.order.length)assert(K.validOrder(result.order));});
test('all stored hero-role skill guides have named legal points or an explicit unavailable reason',()=>{const b=seed(),e=M.create(b);let checked=0;for(const slug of Object.keys(e.heroes))for(const role of e.roles(slug)){const g=K.make(b,e.plannedBuild(slug,role));assert(g.points.length===18||g.reason,slug+' '+role);if(g.points.length){assert(K.validOrder(g.order));assert(g.points.every(p=>p.name&&p.key));}checked++;}assert(checked>=Object.keys(b.heroes).length);});
const {fixture}=require('./build_coach.test.cjs');
function withVariant(){const b=fixture();b.heroes.hero.roles.jungle={status:'ok',builds:[{perk:'Augment',eternal:'Eternal',core_items:{coreItems:['B','A','C']},items4:[{name:'F',playedGames:300}],items5:[{name:'D',playedGames:300}],items6:[{name:'E',playedGames:300}]}]};Object.assign(b.guidance.builds[0],{augment:'Augment',eternal:'Eternal'});return b;}
test('coach uses the selected core order instead of silently replacing it with the reviewed default',()=>{const b=withVariant(),a=M.create(b).adaptBuild({slug:'hero',role:'jungle'},[],[],{variant:0,state:'ahead'});assert.equal(a.available,true);assert.equal(a.plan.manual,true);assert.deepEqual(a.slots.slice(0,3).map(s=>s.name),['B','A','C']);assert.equal(a.nextPurchase.name,'B');assert.equal(a.plan.kind,'provisional');});
test('different selected loadout is retained but cannot borrow the default mechanics review',()=>{const b=withVariant();b.heroes.hero.roles.jungle.builds[0].perk='Different';const a=M.create(b).adaptBuild({slug:'hero',role:'jungle'},[],[],{variant:0});assert.equal(a.available,false);assert.equal(a.plan.augment,'Different');assert.match(a.unavailableReason,/mechanics review/);assert.equal(a.nextPurchase,null);});
test('coach rejects obsolete variant indices instead of falling back',()=>assert.throws(()=>M.create(withVariant()).adaptBuild({slug:'hero',role:'jungle'},[],[],{variant:2}),/unavailable/));
