'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),Meta=require('../engine.js');
const NOW=Date.parse('2026-09-21T20:00:00Z');
function fixture(){return {heroes:{},pairs:[],patch:'1.16',bracket:{segment:'gold',label:'Gold+'},official:{status:'verified',live:{version:'1.16.4'}},guidance:{patch:'1.16.4',status:'reviewed for current patch',reviewed_at:'2026-09-14T10:00:00Z',maintenance_review:{next_weekly_review:'2026-09-20T10:00:00Z'}},sources:{pred_scoped:{status:'retained',fetched_at:'2026-09-21T19:00:00Z'},statz_tierlist:{status:'ok',fetched_at:'2026-09-21T19:30:00Z'},statz_hero_pages:{status:'ok',fetched_at:'2026-09-21T19:30:00Z'}},scoped_statistics:{status:'retained',patch:'1.16.4',bracket:'gold',bracket_label:'Gold+',roles:{}}};}
test('recent retained exact patch takes priority but is explicitly saved',()=>{const b=fixture(),before=JSON.stringify(b),e=Meta.create(b),p=e.performancePolicy({now:NOW});assert.equal(p.source,'pred');assert.equal(p.saved,true);assert.match(p.note,/retained/);assert.equal(JSON.stringify(b),before);});
test('old, future-dated, wrong-patch and wrong-rank retained evidence cannot take priority',()=>{for(const change of [b=>b.sources.pred_scoped.fetched_at='2026-09-19T00:00:00Z',b=>b.sources.pred_scoped.fetched_at='2026-09-22T00:00:00Z',b=>b.scoped_statistics.patch='1.15',b=>b.scoped_statistics.bracket='diamond']){const b=fixture();change(b);assert.equal(Meta.create(b).performancePolicy({now:NOW}).source,'statz');}});
test('a new patch never relabels old statistics or guidance',()=>{const b=fixture();b.official.live.version='1.17';b.guidance.status='needs review';const areas=Meta.create(b).freshnessAreas({now:NOW});assert.equal(areas[0].state,'unavailable');assert.equal(areas[2].patch,'1.16.4');assert.equal(areas[2].state,'fallback');assert.match(areas[2].reason,/Previous guidance/);});
test('overdue guidance is not advertised as newly reviewed by a statistics refresh',()=>{const a=Meta.create(fixture()).freshnessAreas({now:NOW});assert.equal(a[2].state,'fallback');assert.match(a[2].reason,/review.*due/);});
test('missing hero-role sample remains unavailable instead of zero',()=>{const a=Meta.create(fixture()).freshnessAreas({now:NOW,slug:'missing',role:'jungle'});assert.equal(a[0].state,'unavailable');assert.match(a[0].reason,/lack of eligible data/);});
