/* Isolated design preview. Uses the unchanged production engine and saved bundle.
   Prototype state has its own storage namespace and cannot change the installed app. */
'use strict';
const B=window.REVIEW_BUNDLE,E=MetaEngine.create(B),roles=MetaEngine.ROLES;
const labels={jungle:'Jungle',midlane:'Mid',support:'Support',offlane:'Offlane',carry:'Carry'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=u=>/^https?:\/\//.test(u||'')?u:'';
const name=s=>E.heroes[s]?.display_name||s;
const count=v=>Number.isFinite(v)?v.toLocaleString():'unavailable';
const rate=v=>Number.isFinite(v)?v.toFixed(1)+'%':'Unavailable';
const stamp=v=>v?String(v).slice(0,10):'date unavailable';
const $=s=>document.querySelector(s),store='meta-mobile-design-preview-v1';
let saved={};try{saved=JSON.parse(localStorage.getItem(store)||'{}');}catch{}
let S={view:'meta',role:'jungle',hero:'khaimera',section:'build',query:'',pool:[],allies:[],enemies:[],bans:[],selected:{},owned:[],dirty:true,candidates:[],preview:null,theme:'dark',...saved};
let undo=null,dialogOpener=null;
function persist(){try{localStorage.setItem(store,JSON.stringify(S));}catch{}}
function tell(s){$('#status').textContent=s;}
function portrait(slug){const h=E.heroes[slug];return safe(h?.image_url)?`<img class="portrait" src="${esc(h.image_url)}" alt="" loading="lazy">`:'';}
function opts(values,current){return values.map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('');}
function full(route='hero',section='builds'){return `full/#view=${route}&hero=${encodeURIComponent(S.hero)}&role=${encodeURIComponent(S.role)}&tab=${section}&bracket=gold`;}
function source(perf){return perf?`${esc(perf.source)} · ${esc(perf.patch||'patch unconfirmed')} · ${esc(stamp(perf.fetched_at))}${perf.retained?' · retained':''}`:'No qualifying current role sample';}
function stat(slug,role=S.role){const p=E.performance({slug,role});return `<span class="numbers"><strong>${rate(p?.wr)}</strong><small>${p?count(p.played)+' games':'Role data unavailable'}</small></span>`;}
function variantId(b){return JSON.stringify([b.perk,b.eternal,b.core_items?.coreItems||[]]);}
function selectedIndex(slug=S.hero,role=S.role){const id=S.selected[slug+'|'+role];if(!id)return null;return (E.heroes[slug]?.roles?.[role]?.builds||[]).findIndex(b=>variantId(b)===id);}
function planFor(slug=S.hero,role=S.role){const i=selectedIndex(slug,role);return E.plannedBuild(slug,role,i!=null&&i>=0?{index:i,forceObserved:true}:{});}
function describePlan(p){return p.kind==='reviewed'?'Reviewed recommendation':p.manual?'Calculated sequence · selected source playstyle':'Calculated starting selection';}
function fullLink(route='hero',section='builds',label='Full details & source evidence'){return `<a class="full-link" href="${full(route,section)}" target="_blank" rel="noopener">${label} ↗</a>`;}
function warning(p){const due=E.strategyReviewDue();return `<p class="warn">${due.due?'Strategy review due':'Saved guidance'} · reviewed ${esc(stamp(p.reviewed_at||B.guidance?.reviewed_at))} for ${esc(p.patch||B.guidance?.patch||'unconfirmed patch')}. ${!p.items.length?'No eligible current build. ':''}Not a new review.</p>`;}
function itemButton(n,kind='items'){const it=Object.values(B[kind]||{}).find(x=>(x.name||x.display_name)===n);return `<button data-item="${esc(n||'Unavailable')}" data-kind="${kind}">${safe(it?.image_url)?`<img src="${esc(it.image_url)}" alt="" loading="lazy">`:''}<span>${esc(n||'Unavailable')}</span></button>`;}
function setup(p){return `<div class="setup">${[['Augment',p.augment],['Eternal',p.eternal],['Blessing 1',p.blessings?.[0]],['Blessing 2',p.blessings?.[1]],['Crest',p.crest]].map(([label,n])=>`<button data-item="${esc(n||'Unavailable')}" data-kind="${label==='Crest'?'items':'perks'}"><small>${label}</small><b>${esc(n||'Unavailable')}</b></button>`).join('')}</div>`;}
function purchases(p){return `<ol class="purchase-list">${(p.items||[]).map(n=>`<li>${itemButton(n)}</li>`).join('')}</ol>`;}
function buildCard(p,{quick=false}={}){return `<section class="card"><span class="tag">${describePlan(p)}</span><h2>${quick?'Set these before the match':'Your starting build'}</h2>${warning(p)}${p.items.length?`<div class="build-layout"><div>${setup(p)}<p class="source">Choices inherit the recommendation category above; no whole-loadout win rate is claimed.</p></div><div>${quick?'<details><summary>Purchase order after loading in</summary>':''}${purchases(p)}${quick?'</details>':''}</div></div><p>${esc((p.reason||'').split(/(?<=[.!?])\s+/)[0])}</p><details><summary>Why this build & skill priority</summary><p>${esc(p.reason)}</p><p>${esc(p.caution)}</p><p>Skill priority: ${esc((p.skill_priority||[]).join(' → ')||'Unavailable')}</p>${(p.item_notes||[]).map(n=>`<p><strong>${esc(n.item)}</strong> · ${esc(n.reason)}</p>`).join('')}</details>`:'<p>No eligible current starting build. Inspect alternatives or the previous reviewed plan; no empty slots are invented.</p>'}${p.review&&!p.review.active?`<details><summary>Previous guidance · not verified current</summary><p>${esc(p.review.status)}</p>${setup(p.review)}${purchases({items:[...(p.review.core||[]),...(p.review.finish||[])]})}</details>`:''}</section>`;}
function filters(){return `<div class="filters"><label>Role<select id="role">${opts(roles.map(r=>[r,labels[r]]),S.role)}</select></label><label>Rank<select aria-label="Saved preview rank" disabled><option>Gold+ · preview</option></select></label><label>Find a hero<input id="search" type="search" placeholder="Hero name" value="${esc(S.query)}"></label></div>`;}
function heroRows(){return Object.keys(E.heroes).filter(s=>E.roles(s).includes(S.role)&&name(s).toLowerCase().includes(S.query.toLowerCase())).sort((a,b)=>(E.performance({slug:b,role:S.role})?.wr??-1)-(E.performance({slug:a,role:S.role})?.wr??-1)).map(s=>`<button class="hero-row" data-hero="${s}">${portrait(s)}<span class="identity"><strong>${esc(name(s))}</strong><br><small>${labels[S.role]}</small></span>${stat(s)}</button>`).join('');}
function list(){return `<p class="eyebrow">Plan before you play</p><h1>${S.view==='builds'?'Find your build':'Meta'}</h1><p class="muted">${S.view==='builds'?'Choose a hero. Get one clear starting build.':'Pick a role. Find your next hero.'}</p>${filters()}<p class="source">Ordered by available role win rate · samples remain separate. Saved Gold+ preview; this is not a fresh collection.</p><div class="hero-list">${heroRows()||'<p>No heroes match.</p>'}</div>`;}
function alternatives(){const rows=E.heroes[S.hero]?.roles?.[S.role]?.builds||[];return `<h2>Alternative playstyles</h2><p class="muted">Source variants, not a ranking of the best build. The assembled six-item path is calculated.</p><button data-default="true">Use recommended starting build</button>${rows.map((b,i)=>{const p=E.plannedBuild(S.hero,S.role,{index:i,forceObserved:true});return `<article class="card"><span class="tag">Observed variant · Statz</span><h3>${esc(b.perk)} / ${esc(b.eternal)}</h3><p>${rate(b.winRate)} win rate · ${count(b.playedGames)} games</p><p class="source">Dataset ${esc(B.patch)} · exact match window unconfirmed · ${stamp(E.heroes[S.hero].roles[S.role].fetched_at)}</p><details><summary>Compare loadout and purchase path</summary>${setup(p)}${purchases(p)}<p>${esc(p.reason)}</p><p>${esc(p.caution)}</p></details><button data-variant="${i}" class="primary">Choose this playstyle</button></article>`;}).join('')||'<p>No source variants available for this role.</p>'}`;}
function counterplayData(){return RecommendationView.counterplay(E,E.heroes,S.hero,S.role);}
function counters(){
 const data=counterplayData(),strategy=data.strategy,due=E.strategyReviewDue().due;
 const reading=r=>`<p><strong>${rate(r.wr)} ${esc(name(S.hero))} win rate · ${count(r.played)} games</strong></p><p class="source">${esc(r.label||r.source)} · ${esc(r.limitation||'Enemy role unconfirmed.')} · ${stamp(r.fetched_at)}</p>`;
 return `<h2>Playing against ${esc(name(S.hero))}</h2><p class="muted">If you play ${esc(name(S.hero))}, these are the responses to watch for.</p>`+
 data.picks.map(r=>`<article class="card counter-pick"><span class="tag">${r.evidenceKind==='reviewed'?'Reviewed counter-pick':'Observed difficult matchup · not a proven hard counter'}</span><h3>${esc(name(r.slug))}${r.evidenceKind==='reviewed'?' · '+esc(labels[r.role]||r.role):''}</h3>${r.evidenceKind==='reviewed'?`<p>${esc(r.reason)}</p><p class="source">${esc(r.limit||'Execution and team context matter.')}<br>Reviewed ${stamp(r.reviewed_at)} · ${esc(B.guidance.strategic_review.patch)}${due?' · review due':''}</p>${r.observation?reading(r.observation):'<p class="source">Kit-based advice; no qualifying current matchup win rate.</p>'}`:reading(r)}</article>`).join('')+
 (!data.picks.length?'<p class="source">No supported named counter in this saved evidence. That does not mean this hero has no counters.</p>':'')+
 (data.points.length?`<section class="card counterplay-advice"><span class="tag">${strategy.active?'Reviewed counterplay':'Previous reviewed counterplay · needs recheck'}</span><h3>How to play against them</h3>${!strategy.active?'<p class="warn">Previous guidance, not verified for current mechanics.</p>':''}<ol>${data.points.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p class="source">Reviewed ${stamp(strategy.reviewed_at)} · ${esc(strategy.patch)}${due?' · scheduled review due':''}</p></section>`:'')+
 (!data.available?'<p class="warn">Counterplay evidence unavailable. No named counter or matchup is assumed.</p>':'')+
 fullLink('hero','counters','All matchups, reviewed counterplay & sources');
}
function partners(){
 const result=E.partners(S.hero,{min:100,heroRole:S.role,metric:'kit'}),rows=RecommendationView.partnerShortlist(result.combined);
 return `<h2>Five partners to consider</h2><p class="muted">Strong kit fits with a mix of roles where scores are close. This is a shortlist, not a team win-rate prediction.</p>`+
 rows.map(r=>{const reason=r.fit?.reasons?.[0];return `<article class="card partner-card" data-partner-role="${esc(r.role)}"><div class="row spread"><h3>${esc(name(r.slug))}</h3><span class="tag">${esc(labels[r.role]||r.role)}</span></div><small>Kit fit ${Number.isFinite(r.fit?.score)?r.fit.score:'unavailable'} · calculated</small><p>${esc(reason?.summary||reason?.text||'Open the full comparison for ability evidence.')}</p>${reason?.summary&&reason?.text!==reason.summary?`<details><summary>Timing & ability conditions</summary><p>${esc(reason.text)}</p></details>`:''}<a class="full-link" href="${full('hero','pairings')}" target="_blank" rel="noopener">Baseline comparison & samples ↗</a></article>`;}).join('')+
 `<details><summary>How role variety is selected</summary><p>The strongest engine result stays. Different roles can enter within one calculated kit-fit point of the original fifth pick. Remaining places use the original order. Scores and source observations are unchanged; role variety does not establish a stronger pair.</p></details>${fullLink('hero','pairings')}`;
}
function hero(){const p=planFor(),perf=E.performance({slug:S.hero,role:S.role});return `<div class="row hero-head">${portrait(S.hero)}<div><p class="eyebrow">${labels[S.role]} · Gold+</p><h1>${esc(name(S.hero))}</h1></div></div><p class="source">${rate(perf?.wr)} role WR · ${perf?count(perf.played)+' games':'no sample'} · ${source(perf)}</p><div class="section-tabs" aria-label="Hero sections">${[['build','Build'],['alternatives','Alternatives'],['counters','Counterplay'],['partners','Partners'],['kit','Kit']].filter(([id])=>id!=='counters'||counterplayData().available).map(([id,t])=>`<button data-section="${id}" aria-pressed="${S.section===id}">${t}</button>`).join('')}</div>${S.section==='build'?buildCard(p):S.section==='alternatives'?alternatives():S.section==='counters'?counters():S.section==='partners'?partners():`<h2>Hero kit</h2>${(E.heroes[S.hero].abilities||[]).map(a=>`<details><summary>${esc(a.display_name||a.name||a.key)}</summary><p class="detail-text">${esc(a.description||a.text||'Open full details for the source description.')}</p></details>`).join('')}`}${S.section==='build'?'<button class="primary cta" data-adapt="true">Adapt to my match →</button>':''}${fullLink('hero',({build:'builds',alternatives:'builds',partners:'pairings'})[S.section]||S.section)}`;}
function roster(){return `<details><summary>Teammates, enemies & bans · ${S.allies.length+S.enemies.length} picks</summary><h3>Your team</h3><div class="roster">${roles.map(r=>`<button data-slot="allies|${r}">${labels[r]}<span>${esc(name(S.allies.find(p=>p.role===r)?.slug||'Add hero'))}</span></button>`).join('')}</div><h3>Enemy team</h3><div class="roster">${roles.map(r=>`<button data-slot="enemies|${r}">${labels[r]}<span>${esc(name(S.enemies.find(p=>p.role===r)?.slug||'Add hero'))}</span></button>`).join('')}</div><button data-ban="true">Add a ban</button><div class="pool">${S.bans.map(s=>`<button data-unban="${s}">${esc(name(s))} ×</button>`).join('')}</div><p class="source">Changes do not silently reorder the shortlist. Unavailable heroes are disabled immediately.</p></details>`;}
function refreshCandidates(){S.candidates=E.recommend(S.allies.filter(p=>p.role!==S.role),{role:S.role,bans:S.bans,enemies:S.enemies,min:100,metric:'kit'}).map(c=>({slug:c.picks.at(-1).slug,reason:c.links.find(l=>l.a===c.picks.at(-1).slug||l.b===c.picks.at(-1).slug)?.fit?.reasons?.[0]?.text||'Role candidate. Add teammates for a kit interaction; inspect counters separately.'})).filter(c=>!S.pool.length||S.pool.includes(c.slug)).slice(0,3);S.dirty=false;}
function blocked(slug){return S.bans.includes(slug)||[...S.allies,...S.enemies].some(p=>p.slug===slug);}
function draft(){if(!S.candidates.length&&!S.dirty)S.dirty=true;return `<p class="eyebrow">Optional · Quick draft</p><h1>Three choices. One setup.</h1><label>Your role<select id="role">${opts(roles.map(r=>[r,labels[r]]),S.role)}</select></label><details><summary>Your hero pool · ${S.pool.length?S.pool.length+' selected':'all eligible heroes'}</summary><p>Choose up to three familiar heroes. Leave empty to consider everyone.</p><div class="pool">${Object.keys(E.heroes).filter(s=>E.roles(s).includes(S.role)).map(s=>`<button data-pool="${s}" aria-pressed="${S.pool.includes(s)}">${esc(name(s))}</button>`).join('')}</div></details>${roster()}<button class="primary cta" data-refresh="true">${S.candidates.length?'Update suggestions':'Show my shortlist'}</button>${S.dirty&&S.candidates.length?'<p class="notice">Picks changed. Update when you’re ready; the shortlist has stayed in place.</p>':''}<div class="choices">${S.candidates.map(c=>`<article class="card choice"><div class="row">${portrait(c.slug)}<h2>${esc(name(c.slug))}</h2></div><p>${esc(c.reason)}</p><small>Calculated kit-fit ordering</small><button class="primary" data-preview="${c.slug}" ${blocked(c.slug)?'disabled':''}>${blocked(c.slug)?'Picked or banned':'See pre-match setup'}</button></article>`).join('')}</div>${!S.candidates.length?'<p class="muted">No shortlist yet. Fewer than three eligible heroes will show fewer choices.</p>':''}${S.preview?`<h2>${esc(name(S.preview))} · your setup</h2>${buildCard(planFor(S.preview,S.role),{quick:true})}<button class="primary cta" data-lock="${S.preview}" ${blocked(S.preview)?'disabled':''}>Use this hero & continue to match</button>`:''}<button class="cta" data-wide="true">Show other heroes</button>${fullLink('draft','builds','Full Draft, Compose & advanced comparisons')}`;}
function live(){const p=planFor(),i=selectedIndex();let advice;try{advice=E.liveBuild({slug:S.hero,role:S.role},S.allies,S.enemies,{owned:S.owned,variant:i>=0&&i!=null?i:null});}catch(e){return `<h1>Match setup needs attention</h1><p>${esc(e.message)}</p>${roster()}`;}return `<p class="eyebrow">${esc(name(S.hero))} · ${labels[S.role]}</p><h1>Adapt to this match</h1><p class="source">Selected ${p.manual?'source playstyle':'starting recommendation'} is carried forward. Add only what you know.</p>${roster()}<section class="card"><span class="tag">Calculated match adaptation</span><h2>${advice.nextPurchase?'Next: '+esc(advice.nextPurchase.name):advice.available?'Six completed items owned':'No eligible next purchase'}</h2><p>${esc(advice.nextPurchase?.label||advice.unavailableReason||'No automatic sale suggested.')}</p>${advice.available?purchases({items:advice.slots.map(s=>s.name)}):''}${(advice.swaps||[]).map(s=>`<p>${esc(s.from)} → ${esc(s.to)}: ${esc(s.reason)}</p>`).join('')}${warning(p)}</section><details><summary>Completed items you own · ${S.owned.length}/6</summary><label>Add an item<select id="owned"><option value="">Choose a completed item</option>${opts(Object.values(B.items).filter(i=>i.completed_item&&!S.owned.includes(i.name)).sort((a,b)=>a.name.localeCompare(b.name)).map(i=>[i.name,i.name]),'')}</select></label>${S.owned.map(n=>`<button data-remove-owned="${esc(n)}">${esc(n)} ×</button>`).join('')}</details><details><summary>Compare with my starting build</summary>${buildCard(p)}</details><button data-new="true">New match</button>${fullLink('live','builds','Full match advice & evidence')}`;}
function more(){return `<h1>More</h1><p class="muted">The full reference is still here.</p><div class="stack">${[['guidance','Strategy guides'],['library','Items & loadouts'],['changes','Patch & statistics changes'],['data','Sources & accuracy'],['more','Settings, sharing & exports']].map(([r,t])=>`<a class="action" href="${full(r)}" target="_blank" rel="noopener">${t} ↗</a>`).join('')}</div><p class="notice">Preview limitations: one saved Gold+ bundle, separate local state, no auto updates or new offline guarantee. Production data and settings are untouched.</p>`;}
function render({focus=false}={}){document.documentElement.dataset.theme=S.theme;$('#theme').textContent=S.theme==='dark'?'Light':'Dark';$('#main').innerHTML=['meta','builds'].includes(S.view)?list():S.view==='hero'?hero():S.view==='plan'?draft():S.view==='live'?live():more();$('#nav').innerHTML=[['meta','Meta'],['builds','Builds'],['plan','Plan'],['more','More']].map(([id,t])=>`<button data-nav="${id}" ${S.view===id||id==='builds'&&S.view==='hero'||id==='plan'&&S.view==='live'?'aria-current="page"':''}>${t}</button>`).join('');persist();if(focus){$('#main').focus();window.scrollTo(0,0);}}
function go(view){S.view=view;render({focus:true});}
function modal(title,body){dialogOpener=document.activeElement;$('#detail-title').textContent=title;$('#detail-body').innerHTML=body;$('#detail').showModal();$('#close-dialog').focus();}
function snapshot(){undo=JSON.parse(JSON.stringify(S));}
function undoNotice(){tell('Selection updated.');$('#status').innerHTML+=' <button data-undo="true">Undo</button>';}
function picker(side,role){const used=[...S.allies,...S.enemies].filter(p=>!(S[side]?.includes(p)&&p.role===role)).map(p=>p.slug);modal(side==='ban'?'Ban a hero':`${side==='allies'?'Ally':'Enemy'} · ${labels[role]}`,`<label>Find a hero<input id="picker-search" type="search"></label><div id="picker-options" class="stack">${side!=='ban'?`<button data-assign="${side}|${role}|">Clear this slot</button>`:''}${Object.keys(E.heroes).filter(s=>side==='ban'||E.roles(s).includes(role)).map(s=>`<button data-assign="${side}|${role||''}|${s}" ${used.includes(s)||S.bans.includes(s)?'disabled':''}>${esc(name(s))}${used.includes(s)?' · already picked':S.bans.includes(s)?' · banned':''}</button>`).join('')}</div>`);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(b.id==='theme'){S.theme=S.theme==='dark'?'light':'dark';render();}else if(b.id==='close-dialog')$('#detail').close();else if(d.nav){go(d.nav);}else if(d.hero){S.hero=d.hero;S.section='build';go('hero');}else if(d.section){S.section=d.section;render();}else if(d.variant!=null){const v=E.heroes[S.hero].roles[S.role].builds[+d.variant];S.selected[S.hero+'|'+S.role]=variantId(v);S.section='build';render({focus:true});}else if(d.default){delete S.selected[S.hero+'|'+S.role];S.section='build';render();}else if(d.adapt||d.lock){const s=d.lock||S.hero;if(S.bans.includes(s)||S.enemies.some(p=>p.slug===s)){tell('That hero is picked or banned. Choose another.');return;}snapshot();S.hero=s;S.allies=S.allies.filter(p=>p.role!==S.role&&p.slug!==s).concat({slug:s,role:S.role});go('live');undoNotice();}else if(d.refresh){refreshCandidates();render();}else if(d.pool){if(S.pool.includes(d.pool))S.pool=S.pool.filter(s=>s!==d.pool);else if(S.pool.length<3)S.pool.push(d.pool);else{tell('Your pool has three heroes. Remove one to replace it.');return;}S.dirty=true;render();}else if(d.preview){S.preview=d.preview;render();}else if(d.wide){S.pool=[];refreshCandidates();render();}else if(d.slot){picker(...d.slot.split('|'));}else if(d.ban){picker('ban');}else if(d.assign!=null){const [side,role,slug]=d.assign.split('|');if(slug&&(S.bans.includes(slug)||[...S.allies,...S.enemies].some(p=>p.slug===slug&&!(side!=='ban'&&S[side].includes(p)&&p.role===role))))return;snapshot();if(side==='ban')S.bans.push(slug);else S[side]=S[side].filter(p=>p.role!==role).concat(slug?[{slug,role}]:[]);S.dirty=true;$('#detail').close();render();undoNotice();}else if(d.unban){snapshot();S.bans=S.bans.filter(s=>s!==d.unban);S.dirty=true;render();undoNotice();}else if(d.removeOwned){snapshot();S.owned=S.owned.filter(n=>n!==d.removeOwned);render();undoNotice();}else if(d.new){snapshot();S.owned=[];S.allies=[];S.enemies=[];S.bans=[];S.preview=null;S.candidates=[];S.dirty=true;go('plan');undoNotice();}else if(d.undo&&undo){S=undo;undo=null;tell('Change undone.');render();}else if(d.item){const obj=Object.values(B[d.kind]||{}).find(x=>(x.name||x.display_name)===d.item);modal(d.item,`<p class="source">Saved source description · inspect full evidence for corrections and applicability.</p><div class="detail-text">${esc(obj?.description||obj?.text||(obj?.effects||[]).map(x=>[x.name,x.condition,x.text].filter(Boolean).join('\n')).join('\n\n')||'Description unavailable in this source block.')}</div>${fullLink('library','kit','Full item and correction details')}`);}});
document.addEventListener('change',e=>{if(e.target.id==='role'){S.role=e.target.value;S.pool=[];S.candidates=[];S.preview=null;S.dirty=true;render();}else if(e.target.id==='owned'&&e.target.value&&S.owned.length<6){snapshot();S.owned.push(e.target.value);render();undoNotice();}});
document.addEventListener('input',e=>{if(e.target.id==='search'){S.query=e.target.value;$('.hero-list').innerHTML=heroRows();persist();}if(e.target.id==='picker-search'){const q=e.target.value.toLowerCase();$('#picker-options').querySelectorAll('button').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q));}});
$('#detail').addEventListener('close',()=>{if(dialogOpener?.isConnected)dialogOpener.focus();});
document.addEventListener('error',e=>{if(e.target.tagName==='IMG')e.target.hidden=true;},true);
render();
