'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{make,validOrder}=require('./skill-guide');
const order=['Primary','Alternate','Secondary','Primary','Primary','Ultimate','Primary','Alternate','Primary','Alternate','Ultimate','Alternate','Alternate','Secondary','Secondary','Ultimate','Secondary','Secondary'];
function fixture(){return {bundle:{patch:'1.16',heroes:{hero:{abilities:['Q','E','RMB','R'].map(key=>({key,display_name:'Ability '+key,text:'Mechanics '+key})),roles:{jungle:{url:'https://example.test/hero',fetched_at:'2026-09-21',builds:[{perk:'A',eternal:'E',popular_skill_order:{skillOrder:order,winRate:52,playedGames:200}}]}}}}},plan:{slug:'hero',role:'jungle',kind:'reviewed',patch:'1.16.4',augment:'A',eternal:'E',skill_priority:['Primary','Alternate','Secondary'],reviewed_at:'2026-09-14'}};}
test('matching observed order names every point and preserves its own statistics',()=>{const {bundle,plan}=fixture(),g=make(bundle,plan);assert.equal(g.kind,'observed');assert.equal(g.points.length,18);assert.equal(g.points[0].name,'Ability Q');assert.equal(g.points[5].key,'R');assert.equal(g.source.played,200);assert.equal(g.source.patch,'1.16');});
test('another loadout cannot donate its sequence or sample to this plan',()=>{const {bundle,plan}=fixture();plan.eternal='Different';const g=make(bundle,plan);assert.equal(g.kind,'calculated');assert.equal(g.source.played,undefined);assert.equal(g.order.length,18);assert.match(g.label,/needs review/);});
test('an explicit selected variant keeps its exact order',()=>{const {bundle,plan}=fixture();const other=order.map(k=>k==='Primary'?'Alternate':k==='Alternate'?'Primary':k);bundle.heroes.hero.roles.jungle.builds.push({perk:'A',eternal:'E',popular_skill_order:{skillOrder:other}});assert.deepEqual(make(bundle,plan,{variantIndex:1}).order,other);});
test('reviewed priority does not label a generated schedule reviewed',()=>{const {bundle,plan}=fixture();bundle.heroes.hero.roles.jungle.builds=[];const g=make(bundle,plan);assert.equal(g.kind,'calculated');assert.ok(validOrder(g.order));});
test('invalid priorities, unknown ability names and malformed sequences are rejected',()=>{const {bundle,plan}=fixture();bundle.heroes.hero.roles.jungle.builds=[];plan.skill_priority=['Primary','Primary','Secondary'];assert.equal(make(bundle,plan).points.length,0);bundle.heroes.hero.abilities.shift();assert.equal(make(bundle,plan).points.length,0);assert.equal(validOrder(['Primary']),false);const early=[...order];early[0]='Ultimate';assert.equal(validOrder(early),false);});
test('current explicit reviewed skill order requires sources and matching abilities; old patch does not qualify',()=>{const {bundle,plan}=fixture();plan.skill_order_review={order,patch:plan.patch,reviewed_at:'2026-09-14',reason:'Role-specific reviewed opening.',sources:[{url:'https://example.test/hero'}],source_abilities:Object.fromEntries(bundle.heroes.hero.abilities.map(a=>[a.key,a.text]))};assert.equal(make(bundle,plan).kind,'reviewed');bundle.heroes.hero.abilities[0].text='Changed mechanics';assert.equal(make(bundle,plan).kind,'observed');bundle.heroes.hero.abilities[0].text='Mechanics Q';plan.skill_order_review.patch='1.15';assert.equal(make(bundle,plan).kind,'observed');});
test('Revenant exceptional starting rank prevents generic fallback',()=>{const {bundle,plan}=fixture();bundle.heroes.revenant=bundle.heroes.hero;plan.slug='revenant';bundle.heroes.revenant.roles.jungle.builds=[];const g=make(bundle,plan);assert.equal(g.points.length,0);assert.match(g.reason,/starts with a rank/);});
test('Revenant alternative observation explicitly names the different loadout',()=>{const {bundle,plan}=fixture();bundle.heroes.revenant=bundle.heroes.hero;plan.slug='revenant';plan.augment='Other';const g=make(bundle,plan);assert.equal(g.kind,'observed');assert.match(g.label,/different loadout/);assert.match(g.reason,/A \/ E/);});
test('historical priority keeps its inactive warning',()=>{const {bundle,plan}=fixture();plan.kind='provisional';plan.skill_priority=[];plan.review={active:false,skill_priority:['Primary','Secondary','Alternate'],reviewed_at:'2026-09-14'};plan.augment=null;const g=make(bundle,plan);assert.equal(g.kind,'calculated');assert.ok(g.notes.some(x=>/not active/.test(x)));});
